# Generated by Django 4.0.5 on 2023-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual'), ('project', 'Project'), ('platform', 'Platform'), ('operation', 'Operation'), ('instrument', 'Instrument'), ('acquisition_capabilities', 'Acquisition Capabilities'), ('acquisition', 'Acquisition'), ('computation_capabilities', 'Computation Capabilities'), ('computation', 'Computation'), ('process', 'Process'), ('data_collection', 'Data Collection'), ('catalogue', 'Catalogue'), ('catalogue_entry', 'Catalogue Entry'), ('catalogue_data_subset', 'Catalogue Data Subset')], max_length=100)),
                ('xml', models.TextField()),
                ('json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_method', models.CharField(choices=[('api', 'API'), ('micado', 'MiCADO'), ('download', 'Download')], default='api', max_length=100)),
                ('json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='AcquisitionCapabilities',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='CatalogueDataSubset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='CatalogueEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Computation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='ComputationCapabilities',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata',),
        ),
    ]
