# Generated by Django 4.0.5 on 2023-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleURLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_subset_url', models.URLField()),
                ('handle_name', models.CharField(max_length=100)),
            ],
        ),
    ]
