# Generated by Django 4.0.5 on 2023-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_handleurlmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificmetadata',
            name='registration_id',
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
