# Generated by Django 4.0.5 on 2023-06-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_scientificmetadata_registration_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_method', models.CharField(choices=[('api', 'API')], default='api', max_length=100)),
                ('json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TechnicalMetadata',
        ),
        migrations.RenameField(
            model_name='handleurlmapping',
            old_name='data_subset_url',
            new_name='url',
        ),
    ]
