# Generated by Django 4.0.5 on 2023-06-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_json_interactionmethod_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionmethod',
            name='data_collection',
            field=models.ForeignKey(limit_choices_to={'type': 'data_collection'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.datacollection'),
        ),
    ]
