# Generated by Django 4.0.5 on 2023-06-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_interactionmethod_data_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIInteractionMethod',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.interactionmethod',),
        ),
    ]
