# Generated by Django 4.0.5 on 2023-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_interactionmethod_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificmetadata',
            name='institution_id',
            field=models.CharField(db_column='inst_id', default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificmetadata',
            name='owner_id',
            field=models.CharField(db_column='owner_id', default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
