# Generated by Django 5.0.1 on 2025-04-03 10:30

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_workflow_alter_scientificmetadata_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogue',
        ),
        migrations.DeleteModel(
            name='CatalogueDataSubset',
        ),
        migrations.DeleteModel(
            name='CatalogueEntry',
        ),
        migrations.CreateModel(
            name='DataSubset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata', common.models.StaticDatasetTypeDescriptionMixin),
        ),
        migrations.CreateModel(
            name='StaticDataset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata', common.models.StaticDatasetTypeDescriptionMixin),
        ),
        migrations.CreateModel(
            name='StaticDatasetEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.scientificmetadata', common.models.StaticDatasetTypeDescriptionMixin),
        ),
        migrations.CreateModel(
            name='WorkflowAPIInteractionMethod',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.interactionmethod',),
        ),
        migrations.RemoveField(
            model_name='interactionmethod',
            name='data_collection',
        ),
        migrations.AddField(
            model_name='interactionmethod',
            name='scientific_metadata',
            field=models.ForeignKey(db_column='sm_id', limit_choices_to=models.Q(('type', 'data_collection'), ('type', 'workflow'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='common.scientificmetadata'),
        ),
        migrations.AlterField(
            model_name='interactionmethod',
            name='owner',
            field=models.CharField(db_column='owner_id', max_length=200),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='type',
            field=models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual'), ('project', 'Project'), ('platform', 'Platform'), ('operation', 'Operation'), ('instrument', 'Instrument'), ('acquisition_capabilities', 'Acquisition Capabilities'), ('acquisition', 'Acquisition'), ('computation_capabilities', 'Computation Capabilities'), ('computation', 'Computation'), ('process', 'Process'), ('data_collection', 'Data Collection'), ('static_dataset', 'Static Dataset'), ('static_dataset_entry', 'Static Dataset Entry'), ('data_subset', 'Data Subset'), ('workflow', 'Workflow')], db_column='sm_type', max_length=100),
        ),
    ]
