# Generated by Django 5.0.1 on 2025-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_delete_catalogue_delete_cataloguedatasubset_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticDataset',
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='type',
            field=models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual'), ('project', 'Project'), ('platform', 'Platform'), ('operation', 'Operation'), ('instrument', 'Instrument'), ('acquisition_capabilities', 'Acquisition Capabilities'), ('acquisition', 'Acquisition'), ('computation_capabilities', 'Computation Capabilities'), ('computation', 'Computation'), ('process', 'Process'), ('data_collection', 'Data Collection'), ('static_dataset_entry', 'Static Dataset Entry'), ('data_subset', 'Data Subset'), ('workflow', 'Workflow')], db_column='sm_type', max_length=100),
        ),
    ]
