# Generated by Django 5.2.18 on 2026-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_delete_staticdataset_alter_scientificmetadata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmetadata',
            name='owner_id',
            field=models.CharField(db_column='owner_id', max_length=200, null=True),
        ),
    ]
