# Generated by Django 5.2.18 on 2026-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_scientificmetadata_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='sm_reg_date', null=True),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='deactivated',
            field=models.BooleanField(db_column='sm_deactivated', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='institution_id',
            field=models.CharField(db_column='inst_id', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='json',
            field=models.JSONField(db_column='sm_json_support', null=True),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='type',
            field=models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual'), ('project', 'Project'), ('platform', 'Platform'), ('operation', 'Operation'), ('instrument', 'Instrument'), ('acquisition_capabilities', 'Acquisition Capabilities'), ('acquisition', 'Acquisition'), ('computation_capabilities', 'Computation Capabilities'), ('computation', 'Computation'), ('process', 'Process'), ('data_collection', 'Data Collection'), ('static_dataset_entry', 'Static Dataset Entry'), ('data_subset', 'Data Subset'), ('workflow', 'Workflow')], db_column='sm_type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='sm_upd_date', null=True),
        ),
        migrations.AlterField(
            model_name='scientificmetadata',
            name='xml',
            field=models.TextField(db_column='sm_metadata_file', null=True),
        ),
    ]
