# Generated by Django 5.2.18 on 2026-10-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_scientificmetadata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionmethod',
            name='config',
            field=models.JSONField(db_column='intm_config', null=True),
        ),
        migrations.AlterField(
            model_name='interactionmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='intm_reg_date', null=True),
        ),
        migrations.AlterField(
            model_name='interactionmethod',
            name='deactivated',
            field=models.BooleanField(db_column='intm_deactivated', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='interactionmethod',
            name='scientific_metadata',
            field=models.ForeignKey(db_column='sm_id', default='', limit_choices_to=models.Q(('type', 'data_collection'), ('type', 'workflow'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='common.scientificmetadata'),
        ),
        migrations.AlterField(
            model_name='interactionmethod',
            name='type',
            field=models.CharField(choices=[('api', 'API')], db_column='intm_type', default='api', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interactionmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='intm_upd_date', null=True),
        ),
    ]
