# Generated by Django 4.0.3 on 2022-03-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PithiaResourceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localID', models.CharField(max_length=200)),
                ('namespace', models.CharField(max_length=200)),
                ('version', models.IntegerField()),
                ('creationDate', models.DateTimeField()),
                ('lastModificationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pithiaIdentifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.pithiaresourceidentifier')),
            ],
        ),
    ]
