class NamespacePrefix:
    GCO = 'gco'
    GCO19115 = 'gco'
    GMD = 'gmd'
    GML = 'gml'
    MRL = 'mrl'
    OM = 'om'
    PITHIA = ''
    XLINK = 'xlink'
    XSI = 'xsi'

class Namespace:
    GCO = 'http://www.isotc211.org/2005/gco'
    GCO19115 = 'http://standards.iso.org/iso/19115/-3/gco/1.0'
    GMD = 'http://www.isotc211.org/2005/gmd'
    GML = 'http://www.opengis.net/gml/3.2'
    MRL = 'http://standards.iso.org/iso/19115/-3/mrl/1.0'
    OM = 'http://www.opengis.net/om/2.0'
    PITHIA = 'https://metadata.pithia.eu/schemas/2.2'
    XLINK = 'http://www.w3.org/1999/xlink'
    XSI = 'http://www.w3.org/2001/XMLSchema-instance'