# Generated by Django 4.0.3 on 2022-03-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
