name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: default
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-deps
    - name: Create and populate .env file
      env:
        SECRET_KEY: tlR922803zw9IDmFMHXLqd5sn6WfJSKDRYxdEe_l7ZQ
        DATABASE_ENGINE: django.db.backends.postgresql
        DATABASE_NAME: default
        DATABASE_READ_USER: postgres
        DATABASE_READ_PASSWORD: postgres
        DATABASE_WRITE_USER: postgres
        DATABASE_WRITE_PASSWORD: postgres
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 5432
        MONGODB_CONNECTION_STRING: mongodb://localhost:27017
        DB_NAME: test
        DJANGO_RW_DATABASE_NAME: default
      run: |
        touch pithiaesc/.env
        echo SECRET_KEY="$SECRET_KEY" >> pithiaesc/.env
        echo DATABASE_ENGINE="$DATABASE_ENGINE" >> pithiaesc/.env
        echo DATABASE_NAME="$DATABASE_NAME" >> pithiaesc/.env
        echo DATABASE_READ_USER="$DATABASE_READ_USER" >> pithiaesc/.env
        echo DATABASE_READ_PASSWORD="$DATABASE_READ_PASSWORD" >> pithiaesc/.env
        echo DATABASE_HOST="$DATABASE_HOST" >> pithiaesc/.env
        echo DATABASE_PORT="$DATABASE_PORT" >> pithiaesc/.env
        echo DATABASE_WRITE_USER="$DATABASE_WRITE_USER" >> pithiaesc/.env
        echo DATABASE_WRITE_PASSWORD="$DATABASE_WRITE_PASSWORD" >> pithiaesc/.env
        echo MONGODB_CONNECTION_STRING="$MONGODB_CONNECTION_STRING" >> pithiaesc/.env
        echo DB_NAME="$DB_NAME" >> pithiaesc/.env
        echo DJANGO_RW_DATABASE_NAME="$DJANGO_RW_DATABASE_NAME" >> pithiaesc/.env
        
        echo "cat pithiaesc/.env"
        cat pithiaesc/.env
    - name: Verify Organisation XSD validation unit test passes
      run: |
        python manage.py test --exclude-tag=slow --exclude-tag=manual
        python manage.py test validation.tests.OrganisationXSDValidationTestCase
